### PR TITLE
Do not error out on denied error for signatures

### LINKED ISSUE #548: Copying signatures from a registry that
**What steps did you take:**
Create a bundle without any signatures
Push it to a registry that returns errors instead of Not Found errors.
Copy that bundle with the flag `--cosign-signatures` to a different registry.

**What happened:**
The following errors show up:
```
imgpkg: Error: Unable to retrieve the following images:
Image: 'sha256-fdd48d34c530dba1bec8f82a5977529718ba191ec8d06557426524b9bf12b371.sig'
Error:access deniedImage: 'sha256-0b34b25313e01995df0a98e37fae4d15fad8b81e6b4c7986cacf130085f82fe6.sig'
Error:access deniedImage: 'sha256-06a7b4e13b751b43814bff38fad6c3db770c472bf46c23937d6953ee56f4f295.sig'
Error:access deniedImage: 'sha256-479f9579d5049a7629fa6d8fe12c1f9e1c864b5adea8433f9773c041fba1a11a.sig'
Error:access deniedImage: 'sha256-19309486cfea374c354431751a3ece2392f9b8e7f12b3fea71db1684b6553cf8.sig'
```

**What did you expect:**
That the bundle is copied without a problem

**Anything else you would like to add:**
Notice the error message is incorrectly formatted. It should look like 
```
Image: 'sha256-fdd48d34c530dba1bec8f82a5977529718ba191ec8d06557426524b9bf12b371.sig'
Error: access denied
mage: 'sha256-0b34b25313e01995df0a98e37fae4d15fad8b81e6b4c7986cacf130085f82fe6.sig'
Error: access denied
```

**Environment:**

- imgpkg version (use `imgpkg --version`): 0.37.2
- Docker registry used (e.g. `Docker HUB`): Harbor
- OS (e.g. from `/etc/os-release`): Any

---
Vote on this request.

This is an invitation to the community to vote on issues to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible."
👎 "There are other more important things to focus on right now."

We are also happy to receive and review Pull Requests if you want to help work on this issue.

### PR DESCRIPTION
**Pull request by joaopapereira**
Fixes #548

### CODE REVIEW

File: pkg/imgpkg/signature/fetch_signatures_test.go [hunk 1]
```diff
@@ -45,7 +45,32 @@ func TestSignatureRetriever_Signatures(t *testing.T) {
...
+
+		args := imageset.NewUnprocessedImageRefs()
+		args.Add(imageset.UnprocessedImageRef{DigestRef: "registry.io/img@sha256:4c8b96d4fffdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0"})
+		args.Add(imageset.UnprocessedImageRef{DigestRef: "registry.io/img1@sha256:6716afd7a68262a37d3f67681ed9dedf3b882938ad777f268f44d68894531f7a"})
+		args.Add(imageset.UnprocessedImageRef{DigestRef: "registry.io/img2@sha256:56cb33b3b4bc45509c5ff7513ddc6ed78764f9ad5165cc32826e04da49d5462b"})
+		args.Add(imageset.UnprocessedImageRef{DigestRef: "registry.io/img2@sha256:a40a266ca606d8dcbac60b4bb1ec42128ba7063f5eed3a997ec4546edc6cf209"})
+		signatures, err := subject.Fetch(args)
+		require.NoError(t, err)
+
+		require.Equal(t, 2, signatures.Length())
```
Comment (praveenrewar) [inline pkg/imgpkg/signature/fetch_signatures_test.go:70]: (non-blocking) nit: Should we also assert that the 2 signatures are what we are looking for, like the previous test.

**Review by praveenrewar — APPROVED** [review]
LGTM!
