### PR TITLE
Reverse the order of extraction of layers

### LINKED ISSUE #441: imgpkg fails to pull images built using ko
**What steps did you take:**

Build an image using ko from go source code:
1. Set `KO_DOCKER_REPO`
2. Run `ko build --bare .` Image will be pushed

Pull the image using imgpkg:
`imgpkg pull -i <image-name> -o output-folder`

**What happened:**
```
imgpkg pull -i <image-name> -o output-folder
Pulling image '<image-name>'
Extracting layer 'sha256:4f8fe8cf0965687f604adde476ea3d9f80a84cbdf1a65' (1/4)
Extracting layer 'sha256:56f50d47b14e80f3433657fca1e3b7eaec734e8ae7ddf3' (2/4)
Extracting layer 'sha256:4e90e501e39c4cbd569536f5cf6e29fea74d74f61aed94' (3/4)

imgpkg: Error: Extracting image into directory: open output-folder/var/run/ko/HEAD: permission denied
```

**Environment:**

- imgpkg version `0.33.0`
- Docker registry used `Harbor`

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

### PR DESCRIPTION
**Pull request by joaopapereira**
Fixes #441

### CODE REVIEW

**Comment by alexbarbato** [comment]
Any chance anyone has had to look at this?

File: pkg/imgpkg/image/dir_image.go [hunk 1]
```diff
@@ -125,6 +138,23 @@ func (i *DirImage) writeLayer(stream io.Reader) error {
 	return nil
 }
 
+func inWhiteoutDir(fileMap map[string]bool, file string) bool {
+	for {
+		if file == "" {
+			break
```
Comment (praveenrewar) [inline pkg/imgpkg/image/dir_image.go]: `return false`?

File: pkg/imgpkg/image/dir_image.go [hunk 2]
```diff
@@ -125,6 +138,23 @@ func (i *DirImage) writeLayer(stream io.Reader) error {
...
+		}
+		dirname := filepath.Dir(file)
+		if file == dirname {
```
Comment (praveenrewar) [inline pkg/imgpkg/image/dir_image.go:147]: Since `filepath.Dir()` returns the files directory, under what circumstances would these be equal? Or are we just trying to be on the safer side?

File: pkg/imgpkg/image/dir_image.go [hunk 3]
```diff
@@ -125,6 +138,23 @@ func (i *DirImage) writeLayer(stream io.Reader) error {
...
+			break
```
Comment (praveenrewar) [inline pkg/imgpkg/image/dir_image.go]: `return false`?

File: pkg/imgpkg/image/dir_image.go [hunk 4]
```diff
@@ -175,7 +202,9 @@ func (i *DirImage) extractTarEntry(header *tar.Header, input io.Reader) error {
 	case tar.TypeLink, tar.TypeSymlink:
 		// skipping symlinks as a security feature
 		return nil
-
```
Comment (praveenrewar) [inline pkg/imgpkg/image/dir_image.go:178]: nit: keep newline

File: test/perf/assets/cf-for-k8s-bundle/.imgpkg/images.yml [hunk 5]
```diff
@@ -41,8 +41,8 @@ images:
     kbld.carvel.dev/id: cloudfoundry/syslog-server@sha256:bb1aa0d603eff716245f25c832ad9b9bca569059f48bd2b5a9a792486f453427
   image: index.docker.io/cloudfoundry/syslog-server@sha256:bb1aa0d603eff716245f25c832ad9b9bca569059f48bd2b5a9a792486f453427
 - annotations:
-    kbld.carvel.dev/id: gcr.io/paketo-community/python@sha256:5fc81b8f38f326f0247468c14b4eb66b36e5f925db12f9ea8df1ec57f9e61d94
-  image: gcr.io/paketo-community/python@sha256:5fc81b8f38f326f0247468c14b4eb66b36e5f925db12f9ea8df1ec57f9e61d94
+    kbld.carvel.dev/id: index.docker.io/paketocommunity/python/python@sha256:1228cfb8003f830b178b9b8a227889cae32df1aed74a746f2ac59b6bb8e88961
```
Comment (praveenrewar) [inline test/perf/assets/cf-for-k8s-bundle/.imgpkg/images.yml:44]: Do we want to merge this in a separate PR first because we might want to cherry pick this to some other branches too.

Comment (joaopapereira) [reply test/perf/assets/cf-for-k8s-bundle/.imgpkg/images.yml:44]: I was expecting this to be merged soon so I just added as part of this PR

File: pkg/imgpkg/image/dir_image.go (hunk 2 above)
Comment (joaopapereira) [reply pkg/imgpkg/image/dir_image.go:147]: In case you call the function with a directory, which should not happen, but it is there just to be safe

**Review by praveenrewar — APPROVED** [review]
