### PR TITLE
Ensure that pushed images can be pulled in different OS

### LINKED ISSUE #271: [windows] imgpkg pushing a bundle on windows cannot be pulled on linux
Related to: https://github.com/vmware-tanzu/carvel-imgpkg/issues/268

**What steps did you take:**

On windows
```
> imgpkg.exe push -f test\e2e\assets\bundle_file_permissions -b image
> imgpkg pull -b image -o ./perms
Succeeds
```

On Linux
```
> imgpkg pull -b image -o ./perms
imgpkg: Error: Reading path /tmp/perms/.imgpkg/images.yml: open /tmp/perms/.imgpkg/images.yml: no such file or directory
```

**What happened:**
linux is unable to find `images.yml` I think due to windows imgpkg using backslashes and linux expecting forward slashes.

**What did you expect:**
imgpkg pull to work on linux

**Environment:**

- imgpkg version (use `imgpkg --version`): 0.19.0
- Docker registry used (e.g. `Docker HUB`): 
- OS (e.g. from `/etc/os-release`): Windows 10

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

### PR DESCRIPTION
**Pull request by joaopapereira**
Fixes #271

### CODE REVIEW

File: pkg/imgpkg/image/tar_image.go [hunk 1]
```diff
@@ -128,9 +137,26 @@ func (i *TarImage) addFileToTar(fullPath, relPath string, info os.FileInfo, tarW
...
+
+		// Due to the difference of line endings on windows this next block will do a dos2unix of the file
+		// before writing it to the tar
+		b, err := ioutil.ReadAll(file)
+		if err != nil {
+			return err
+		}
+		b = regexp.MustCompile(`\r\n`).ReplaceAllLiteral(b, []byte{'\n'})
+		size = int64(len(b))
+		r = bytes.NewBuffer(b)
```
Comment (cppforlife) [inline pkg/imgpkg/image/tar_image.go]: hmm, this doesnt feel right to me for 2 reasons:
- we are reading in entire file contents into memory
- we are modifying contents without explicit user ask (e.g. this will destroy binary files).

**Comment by cppforlife** [comment]
im assuming https://github.com/vmware-tanzu/carvel-imgpkg/issues/271 is related to paths which i think is reasonable to normalize. 

regarding https://github.com/vmware-tanzu/carvel-imgpkg/issues/268, i think it's important for us not to mangle files that user gives us (unless explicitly requested; not sure though that's really job of imgpkg to "fix encodings" since we are content agnostic). whatever was put into a bundle, should come out with exactly same shas on the other end.

**Comment by joaopapereira** [comment]
If we look at #268 right now imgpkg is creating images with different digest for the same content in windows and UNIX systems. This is due to the carriage returns.
An example of that would be if you do a git clone of a repository in UNIX and also in windows and you create an image from it, it should have the same sha but right now it does not.
So in some sense, I believe that imgpkg to keep the guarantee that for the same content we have the same sha we need to do the encoding fixing.

The binary format indeed is a problem. I will look into possibilities to ensure that we can check if a file is binary or not in a simple and less costly way.

**Comment by cppforlife** [comment]
> If we look at https://github.com/vmware-tanzu/carvel-imgpkg/issues/268 right now imgpkg is creating images with different digest for the same content in windows and UNIX systems. This is due to the carriage returns.

it's not the same content though. if you shasum the content it will be different on unix vs windows, right? given that i wouldnt expect that imgpkg would not produce the same digest.

> An example of that would be if you do a git clone of a repository in UNIX and also in windows and you create an image from it, it should have the same sha but right now it does not.

git clone works on text, unlike imgpkg which works on files with arbitrary content. we have no idea what's inside these files and whether it's ok or not ok to modify them.

> The binary format indeed is a problem. I will look into possibilities to ensure that we can check if a file is binary or not in a simple and less costly way.

i think best that can be done with detection is guessing on X number of bytes, but that's pretty hacky.

question related to this topic: what does tar do? since imgpkg is pretty similar to tar in spirit.

**Comment by joaopapereira** [comment]
> question related to this topic: what does tar do? since imgpkg is pretty similar to tar in spirit.

looked into tar and it does nothing, so I will revert my changes
